### PR TITLE
added workaround for gcc 4.9.1 compiler bug (compile using gcc 4.8)

### PR DESCRIPTION
**Pull request by planthaber**

### CODE REVIEW

**Comment by jmachowinski** [comment]
This patch does not guarantee that the GCC 4.8 is actually installed....

**Comment by planthaber** [comment]
Yes, but it gives a correct error message "g++4.8 not found".

So it is up to the user to decide whether to install it or not.

Still this is WAY better than running into a cryptic compiler bug, that is not so easily solved.

**Comment by goldhoorn** [comment]
Uh i don't this compiler forcing behavior. Is there to way to change the code that it is compatible to both compilers?

**Comment by planthaber** [comment]
the gcc bug was fixed by 18584f51017f5f8302aac095aeed87b1452fd638

**Pull request closed without merging**
